FROM docker.io/library/php:7.4-apache
LABEL version="1.0" description="nosqli-labs apache image" image.authors="jose@monkey.org"

# php driver mongodb-1.5.0 is (probably) last one to support mongodb-4.0
# php 7.4 is (probably) the last to support that driver
RUN : \
    && apt-get update -y \
    && apt-get install -y \
	git \
	libssl-dev \
	libcurl4-openssl-dev \
    && apt-get -qq update \
    && pecl install mongodb-1.5.0 \
    && docker-php-ext-enable mongodb \
    && apt-get -qy autoremove \
    && apt-get clean \
    && echo "extension=mongodb.so" > /usr/local/etc/php/conf.d/mongodb.ini

COPY . /var/www/html

RUN : \
	&& sed -i s/"localhost:27017"/"mongo:27017"/g /var/www/html/user_lookup.php \
	&& sed -i s/"localhost:27017"/"mongo:27017"/g /var/www/html/populate_db.php \
	&& sed -i s/"localhost:27017"/"mongo:27017"/g /var/www/html/guess_the_key.php \
	&& sed -i '1s/^/ServerName nosqlilab\n/' /etc/apache2/sites-enabled/000-default.conf
